### ISSUE TITLE
Fix express bugs

### ISSUE THREAD

**Issue by ptmaroct** [daytimedrinkingclub/shipstation#12]
1. Redirect non / ending sites to /, like https://shipstation.ai/site/sam-altman-spotify-portfolio-66Qmav1g/
2. Reloading Code editor screen gives 404, https://shipstation.ai/project/traverse-legal-funny-website-TRWnRl8d

**Comment by CodeMaster17** [comment]
Hey @ptmaroct 
I was looking forward to work on this bug.
Can you please explain the bug
"Redirect non / ending sites to /, like https://shipstation.ai/site/sam-altman-spotify-portfolio-66Qmav1g/ "

**Comment by PREMPRAKASHSINGH** [comment]
@ptmaroct point no 2 - Reloading Code editor screen gives 404 because that is a client side route `/project/:shipId` in `App.jsx` file.

When we refresh the page, the server tries to find a matching route on the server, but since the routing is handled by React on the client side, it returns a 404 error.

Raised a PR for fix of this - #29

**Comment by pramaths** [comment]
@ptmaroct  resolved point no-1 Redirect non / ending sites to /, like https://shipstation.ai/site/sam-altman-spotify-portfolio-66Qmav1g/

Raised PR- https://github.com/daytimedrinkingclub/shipstation/pull/30

**Comment by satvik2131** [comment]
is this issue solved  ?
